#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/CarParts
    username: postgres
    password: masterkey
    initialization-mode: always
  data.rest:
    basePath: /api
    return-body-on-create: true
#  security:
#    user:
#      name: user
#      password: password
#      roles: USER
logging:
  level:
    root: WARN
    ru.skipp.autopartstore: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG


